import { Star, Verified } from 'lucide-react';

const ReviewsData = [
  {
    id: 1,
    name: 'Mary Wald',
    time: '7 hours ago',
    text: 'Aharon was very knowledgeable. He answered all my questions and was very polite and kind.',
    rating: 5,
    verified: true,
  },
  {
    id: 2,
    name: 'John Doe',
    time: '2 days ago',
    text: 'Great service! I\'m very satisfied with the support I received.',
    rating: 3,
    verified: false,
  },
  {
    id: 3,
    name: 'Alice Smith',
    time: '1 week ago',
    text: 'I had a wonderful experience. The team was very helpful and attentive.',
    rating: 4,
    verified: true,
  },
  {
    id: 4,
    name: 'Bob Johnson',
    time: '2 weeks ago',
    text: 'The service was okay, but I expected more.',
    rating: 3,
    verified: true,
  },
  {
    id: 5,
    name: 'Charlie Brown',
    time: '3 weeks ago',
    text: 'Not bad, but there were some issues that need to be addressed.',
    rating: 3,
    verified: false,
  },
  {
    id: 6,
    name: 'David Wilson',
    time: '1 month ago',
    text: 'The product was defective and didn\'t work as expected.',
    rating: 1,
    verified: false,
  },
  {
    id: 7,
    name: 'Emily Davis',
    time: '2 months ago',
    text: 'I wasn\'t happy with the service. It didn\'t meet my expectations.',
    rating: 2,
    verified: false,
  },
  {
    id: 8,
    name: 'Frank Miller',
    time: '3 months ago',
    text: 'The service was terrible. I will not be returning.',
    rating: 1,
    verified: true,
  },
  {
    id: 9,
    name: 'Grace Lee',
    time: '4 months ago',
    text: 'I had a fantastic experience! Highly recommend.',
    rating: 5,
    verified: true,
  },
  {
    id: 10,
    name: 'Henry Adams',
    time: '5 months ago',
    text: 'The service was mediocre at best.',
    rating: 2,
    verified: false,
  },
  {
    id: 11,
    name: 'Isabella Martinez',
    time: '6 months ago',
    text: 'Absolutely loved the service! Will be back for sure.',
    rating: 5,
    verified: true,
  },
  {
    id: 12,
    name: 'James Wilson',
    time: '7 months ago',
    text: 'The experience was just okay, nothing special.',
    rating: 3,
    verified: false,
  },
];

export default ReviewsData;